config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "pages#home"
  # get '/recipes', to: 'recipes#index'
  # get '/recipes/new', to: 'recipes#new'

  # get '/recipes/:id', to: 'recipes#show', as: 'recipe'
  resources :recipes
  get '/signup' , to:'chefs#new'
  resources :chefs

  get '/login', to: 'sessions#new'
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chef.rb
class Chef < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :chefname, presence: true, length: { maximum: 30 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    has_many :recipes
    has_secure_password
    validates :password, presence: true, length: { minimum: 5 }, allow_nil: true

    has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates :description, presence: true, length: { minimum: 4, maximum: 140 }
    belongs_to :chef
    belongs_to :recipe 
    validates :chef_id, presence: true
    validates :recipe_id, presence: true
    default_scope -> { order(updated_at: :desc)}
  end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    validates :name, presence: true, length: { minimum: 3, maximum: 25 }
    validates_uniqueness_of :name
    has_many :recipe_ingredients
    has_many :recipes, through: :recipe_ingredients
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    validates :name, presence: true
    validates :desciption, presence: true, length: {minimun: 5, maximum:500}
    belongs_to :chef
    validates :chef_id, presence: true
    has_many :recipe_ingredients
    has_many :ingredients, through: :recipe_ingredients

    has_many :comments, dependent: :destroy
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
    belongs_to :ingredient 
    belongs_to :recipe
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_chef, :logged_in?

    def current_chef
        @current_chef ||= Chef.find(session[:chef_id]) if session[:chef_id]
    end

    def logged_in?
        !!current_chef
    end

    def require_user
        if !logged_in?
            flash[:danger] = "You must be logged in to perform that action"
            redirect_to root_path
        end
    end
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController

    def index 
      @chef = Chef.all
    end

    def new 
      @chef = Chef.new
    end

    def create
      @chef = Chef.new(chef_params)
      if @chef.save
        flash[:success] = "Welcome #{@chef.chefname} to MyRecipes App!"
        redirect_to chef_path(@chef)
      else
        render 'new'
      end
    end

    def show
      @chef = Chef.find(params[:id])
    end

    def edit
      @chef = Chef.find(params[:id])
    end
    
    def update
      @chef = Chef.find(params[:id])
      if @chef.update(chef_params)
        flash[:success] = "Your account was updated successfully"
        redirect_to @chef
      else
        render 'edit'
      end  
    end

    def destroy
      @chef = Chef.find(params[:id])
      @chef.destroy
      flash[:danger] = "Chef and all associated recipes have been deleted"
      redirect_to chefs_path
    end


    private
  
    def chef_params
      params.require(:chef).permit(:chefname, :email, 
                                      :password, :password_confirmation)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to recipes_path if logged_in?
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    def index
        @recipes = Recipe.all
    end

    def show
        @recipe = Recipe.find(params[:id])
    end

    def new
        @recipe = Recipe.new
    end


    def create
        @recipe = Recipe.new(recipe_params)
        @recipe.chef = current_chef
        if @recipe.save
          flash[:success] = "Recipe was created successfully!"
          redirect_to recipe_path(@recipe)
        else
          render 'new'
        end
    end

    def edit
        @recipe = Recipe.find(params[:id])
    end
    def update
        @recipe = Recipe.find(params[:id])
        if @recipe.update(recipe_params)
            flash[:success] = "Recipe was updated successfully!"
            redirect_to recipe_path(@recipe)
        else
          render 'edit'
        end 
    end

    def destroy
        Recipe.find(params[:id]).destroy
        flash[:success] = "Recipe deleted successfully"
        redirect_to recipes_path
      end
              
    private
    
        def recipe_params
        params.require(:recipe).permit(:name, :desciption)
        end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        # will simply render the form
        end
      
        def create
            chef = Chef.find_by(email: params[:session][:email].downcase)
            if chef && chef.authenticate(params[:session][:password])
              session[:chef_id] = chef.id
              flash[:success] = "You have successfully logged in"
              redirect_to chef
            else
            flash.now[:danger] = "There was something wrong with your login information"
              render 'new'
            end
          end
          
          def destroy
            session[:chef_id] = nil
            flash[:success] = "You have logged out"
            redirect_to root_path
          end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chefs/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= form_for(@chef, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :chefname ,"Choose a name"%>
        </div>
        <div class="col-md-8">
          <%= f.text_field :chefname, class: "form-control", placeholder: "Enter your name", 
                                                                       autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :email %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :email, rows: 10, class: "form-control", 
                                    placeholder: "Enter email" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :password %>
        </div>
        <div class="col-md-8">
          <%= f.password_field :password, rows: 10, class: "form-control", 
                                    placeholder: "Enter password" %>
        </div>
        <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :password_confirmation, "Confirm Password" %>
        </div>
        <div class="col-md-8">
          <%= f.password_field :password_confirmation, rows: 10, class: "form-control", 
                                    placeholder: "Re-enter password" %>
        </div>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit "Create my account", class: "btn btn-primary btn-lg btn-xlarge" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/chefs/edit.html.erb
<h1 style=" margin: 2rem auto ">Edit Your Profile</h1>


<%= render '/chefs/form', obj: @chef %> 

app/views/chefs/index.html.erb
<h1 align="center">Listing all Chefss</h1>
<h5><%= link_to "Add new Chef", new_chef_path %><h5>
<% @chef.each do |recipe| %>
  <div class="row">
    <div class="col-md-2">
      <section class="center">
        
      </section>
    </div>
    <div class="col-md-8 well">
      <h4><%= link_to recipe.chefname , chef_path(recipe)%></h4>
      <p><%= truncate(recipe.email, length: 150) %></p>
      <small><%= pluralize(recipe.recipes.count, "recipe") if recipe.recipes %>
            </small>
      <p>
        <span class="quiet"><small>Created 

        <%= time_ago_in_words(recipe.created_at) %> ago</small></span>
        <p><%= button_to   "Delete chefs", chef_path(recipe), method: :delete, 
                        data: {confirm: "Are you sure you want to delete this chef and all associated recipes?"} , class: "btn btn-danger btn-lg" %></p>
      </p> 
    </div>
   </div>
<% end %>

app/views/chefs/new.html.erb
<h1 style=" margin: 2rem auto ">Signup Form</h1>


<%= render '/chefs/form', obj: @chef %> 

app/views/chefs/show.html.erb
<h1 style="text-align:center; margin: auto "><%= "Chef #{@chef.chefname}'s profile" %></h1>
<%= render 'recipes/recipe', obj: @chef.recipes %>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <a href="#" class="close" data-dismiss="alert">×</a>
        <%= msg %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-light" >
  <div class="container-fluid" >
    <%= link_to "MyRecipes", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" <%= link_to "Recipes", recipes_path%></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" <%= link_to "Chefs", chefs_path%></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
        <li><%= button_to 'Log out', logout_path, method: :delete %></li>


        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myrecipes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <div class="container">
  <%= yield %>
  </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron center">
  <h1>Welcome to MyRecipes</h1>
  <p><%= link_to "Sign up", "signup", class: "btn btn-danger btn-lg" %></p>
  
  <p><%= link_to "login", "login", class: "btn btn-danger btn-lg" %>  </p> 
  <p><%= link_to "See all the recipes", recipes_path, class: "btn btn-danger btn-lg" %></p>
  <p><%= link_to "See all the Chefs", chefs_path, class: "btn btn-danger btn-lg" %></p>

</div>

<hr>
<div class="row">
  <div class="col-lg-4">
    <h2>Heading</h2>
    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
    <p><a class="btn btn-primary btn-xlarge" href="#" role="button">View details »</a></p>
  </div>
  <div class="col-lg-4">
    <h2>Heading</h2>
    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
    <p><a class="btn btn-primary btn-xlarge" href="#" role="button">View details »</a></p>
 </div>
  <div class="col-lg-4">
    <h2>Heading</h2>
    <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
    <p><a class="btn btn-primary btn-xlarge" href="#" role="button">View details »</a></p>
  </div>
</div>

app/views/recipes/_recipe.html.erb
<% obj.each do |recipe| %>
    <div class="row">
      
      <div class="col-md-8 well">
        <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
        <p><%= truncate(recipe.desciption, length: 150) %></p>
        <p>
          <span class="quiet"><small>Created 
          <%= time_ago_in_words(recipe.created_at) %> ago</small></span>
        </p> 
      </div>
    </div>
  <% end %>

app/views/recipes/edit.html.erb
<h1 style=" margin: 2rem auto ">Edit the recipe</h1>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@recipe, :html => {class: "form-horizontal", 

                                                                 role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :name %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :name, class: "form-control", 

                                                 placeholder: "Name of recipe", 
                                                                       autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :desciption %>
        </div>
        <div class="col-md-8">
          <%= f.text_area :desciption, rows: 10, class: "form-control", 
                                    placeholder: "Enter steps to create recipe" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit class: "btn btn-primary btn-lg btn-xlarge" %>
        </div>
      </div>
    <% end %>
    <div class="col-md-4 col-md-offset-4 colormatch">
      [ <%= link_to "Cancel request and return to recipes listing", recipes_path %> ]
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<h1 align="center">Listing all recipes</h1>
<h3><%= link_to "Add new recipes", new_recipe_path %></h3>
<% @recipes.each do |recipe| %>
  <div class="row">
    <div class="col-md-2">
      <section class="center">
        
      </section>
    </div>
    <div class="col-md-8 well">
      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
      <p><%= truncate(recipe.desciption, length: 150) %></p>
      <p>
        <span class="quiet"><small>Created 

        <%= time_ago_in_words(recipe.created_at) %> ago</small></span>
      </p> 
    </div>
  </div>
<% end %>

app/views/recipes/new.html.erb
<h1 style=" margin: 2rem auto ">create a new recipe</h1>
<% if @recipe.errors.any? %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(@recipe.errors.count, "error") %>
            prohibited this <%= @recipe.class %> from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% @recipe.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>  
      </div>
    </div>
  </div>
<% end %>
<div class="row">
  <div class="col-md-12">
    <%= form_for(@recipe, :html => {class: "form-horizontal", 

                                                                 role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :name %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :name, class: "form-control", 

                                                 placeholder: "Name of recipe", 
                                                                       autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :desciption %>
        </div>
        <div class="col-md-8">
          <%= f.text_area :desciption, rows: 10, class: "form-control", 
                                    placeholder: "Enter steps to create recipe" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit class: "btn btn-primary btn-lg btn-xlarge" %>
        </div>
      </div>
    <% end %>
    <div class="col-md-4 col-md-offset-4 colormatch">
      [ <%= link_to "Cancel request and return to recipes listing", 

                                                                               recipes_path %> ]
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="card" style="height: 20rem ;width: 58rem; margin: 2rem auto ">
  <div class="card-body" style="text-align: center;">
    <h5 class="card-title"><%=@recipe.name%></h5>
    <p class="card-text"><%=@recipe.desciption%></p>
    <small><%= @recipe.chef.chefname %></small>
      <div class="pull-right">
        <%= time_ago_in_words(@recipe.created_at) %> ago
      </div>
  </div>
  <div class="recipe-actions">
  <%= link_to "Edit this recipe", edit_recipe_path(@recipe), 

                                                class: 'btn btn-xs btn-warning' %>
  <%= button_to "Delete this recipe", recipe_path(@recipe), method: :delete,
                                    data: { confirm: "Are you sure you want to delete?" },
                                    class: "btn btn-xs btn-danger" %>
</div>  
<%= link_to "return to recipes listing", recipes_path %> 
</div>